version: "3.5"
services:
  go-course-web:
    platform: linux/amd64
    container_name: curso_go_seccion_5_course
    build:
      context: ./.dockers/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: curso_go_seccion_5_course
    ports:
      - "3321:3306"
    volumes:
      - ./.dockers/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql